apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-tasks-config
data:
  POSTGRES_DB: tasksdb
  POSTGRES_USER: devops
  # Important : correspond à la clé demandée par votre backend
  BACKEND_PORT: "3000"
  DATABASE_HOST: postgres-service